/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { useRouter } from "next/router";
export default function Navbar() {
  const router = useRouter();

  React.useEffect(() => {
    setActiveRoute(router.asPath);
    if (show) {
      setShow(false);
    }
  }, [router.asPath]);
  const links = [
    { id: 0, text: "Home", href: "/" },
    { id: 1, text: "Solutions", href: "/solutions" },
    { id: 2, text: "Order", href: "/order" },
    { id: 3, text: "Pricing", href: "/pricing" },
    { id: 4, text: "Portal", href: "/portal" },
  ];
  const [show, setShow] = React.useState(false);
  const [activeRoute, setActiveRoute] = React.useState("/");
  return (
    <div className="wrapper  right-0 left-0 z-[99999] fixed">
      <Head>
        <title>Clean IOT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@300;400;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="container mx-auto shadow-lg sticky top-0">
        <div className="topnav lg:hidden relative z-[99999] bg-gray">
          <div className="logo flex w-full justify-between p-5">
            <Image
              src="/logo-detail.png"
              alt="Vercel Logo"
              width={140}
              height={50}
            />
            <button onClick={() => setShow(!show)}>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 24 24"
                fill="#000"
                stroke="#000"
                strokeWidth={3}
              >
                <line x1="3" y1="12" x2="21" y2="12"></line>
                <line x1="3" y1="6" x2="21" y2="6"></line>
                <line x1="3" y1="18" x2="21" y2="18"></line>
              </svg>
            </button>
          </div>
          {show ? (
            <div id="myLinks">
              {links.map((item, index) => (
                <Link key={index} href={item.href} legacyBehavior>
                  <a
                    style={{
                      backgroundColor: activeRoute === item.href ? "#ccc" : "",
                    }}
                    className="navbar-item hover:bg-darkGray px-5 font-bold text-black text-sm h-[50px] flex items-center"
                  >
                    {item.text}
                  </a>
                </Link>
              ))}
              <Link href="/contact" legacyBehavior>
                <a className="navbar-item font-bold text-sm px-5  text-black h-[50px] flex items-center">
                  Contact
                </a>
              </Link>
            </div>
          ) : null}
        </div>
        <div className="navbar bg-gray w-full p-2.5 hidden lg:flex  ">
          <div className="navbar-content container ml-auto mr-auto flex justify-between">
            <div className="navbar-logo flex items-center justify-center">
              <Image
                src="/logo-detail.png"
                alt="Vercel Logo"
                width={140}
                height={50}
              />
            </div>
            <div className="navbar-menu w-1/3 flex justify-between">
              {links.map((item, index) => (
                <Link
                  key={index}
                  href={item.href}
                  className="navbar-item hover:bg-darkGray px-5 font-bold text-black text-sm h-[50px] flex items-center"
                >
                  {item.text}
                </Link>
              ))}
            </div>
            <div className="mr-right">
              <Link
                href="/contact"
                className="navbar-item bg-darkGray font-bold text-sm px-10  text-black h-[50px] flex items-center"
              >
                Contact
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
